# Generated by staticimports; do not edit by hand.

`%||%` <- function(a, b) {
  if (is.null(a)) b else a
}

add_class <- function(x, class) {
  class(x) <- class
  x
}

map <- function(.x, .f, ...) {
  lapply(.x, .f, ...)
}

map_chr <- function(.x, .f, ...) {
  if (is.character(.f)) {
    vapply(.x, `[[`, .f, ..., FUN.VALUE = NA_character_)
  } else {
    vapply(.x, .f, ..., FUN.VALUE = NA_character_)
  }
}

map_int <- function(.x, .f, ...) {
  if (is.character(.f)) {
    vapply(.x, `[[`, .f, ..., FUN.VALUE = NA_integer_)
  } else {
    vapply(.x, .f, ..., FUN.VALUE = NA_integer_)
  }
}

map_lgl <- function(.x, .f, ...) {
  if (is.character(.f)) {
    vapply(.x, `[[`, .f, ..., FUN.VALUE = NA)
  } else {
    vapply(.x, .f, ..., FUN.VALUE = NA)
  }
}

map2 <- function(.x, .y, .f, ...) {
  mapply(.f, .x, .y, ..., SIMPLIFY = FALSE)
}

named_chr <- function() named_chr_val

named_chr_val <- structure(character(0), .Names = character(0))

named_list <- function() named_list_val

named_list_val <- structure(list(), .Names = character(0))
